#! /bin/bash

serverURL=http://www.ebi.ac.uk
resourcePATH=europepmc/webservices/rest/search
request=query=crystal+structure

pageSize=1000
cursorMark='*'

options="&pageSize=$pageSize"
queryURL="$serverURL/$resourcePATH?$request$options"

xmlresult="$(curl -sSL "$queryURL&cursorMark=$cursorMark")"
echo "$xmlresult"
cursorMark=$(echo "$xmlresult" \
    | tidy -utf8 -xml -i -q \
    | perl -077 -ne 'print $1 if /<nextCursorMark>(.*?)<\/nextCursorMark>/ms')
 
n=$(echo "$xmlresult" \
    | tidy -utf8 -xml -i -q \
    | perl -077 -ne 'print $1 if /<hitCount>(.*?)<\/hitCount>/ms')

j=$(expr $n / $pageSize)

echo n=$n
echo j=$j
echo cursorMark=$cursorMark

if [ $(expr $n % $pageSize) -eq 0 ]
then
    j=$(expr $j - 1)
fi

for i in $(seq 1 $j) ;
do
    xmlresult="$(curl -sSL "$queryURL&cursorMark=$cursorMark")"
    echo "$xmlresult"
    cursorMark=$(echo "$xmlresult" \
    | tidy -utf8 -xml -i -q \
    | perl -077 -ne 'print $1 if /<nextCursorMark>(.*?)<\/nextCursorMark>/ms')
    echo i=$i
done
