#! /bin/bash
#------------------------------------------------------------------------------
#$Author$
#$Date$
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#* Download bibliographies from Europe-PMC, output into an xml format.  
#**

WORKER_SCRIPT=$(dirname $0)/europepmc-json

while [ $# -gt 0 ]
do
    case $1 in
        --help|--hel|--he|--h|\
        --version|--versio|--versi|--vers|--ver|--ve|--v)
            ${WORKER_SCRIPT} "$1" \
                | sed "s/$(basename ${WORKER_SCRIPT})/$(basename $0)/"
            exit 0
            ;;
        *)  FILES="${FILES} '$1'" ;;
    esac
    shift
done

eval set -- "${FILES}"

${WORKER_SCRIPT} --xml-output ${1+"$@"}
