#! /bin/bash
#------------------------------------------------------------------------------
#$Author$
#$Date$
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#* Download bibliographies from Europe-PMC, output into an xml format.  
#**

$(dirname $0)/europepmc-json --xml-output ${1+"$@"}
