#! /bin/bash
#------------------------------------------------------------------------------
#$Author$
#$Date$
#$Revision$
#$URL$
#------------------------------------------------------------------------------
#*
# This script is made to collect search results on europepmc website :
# User enters the search terms as arguments of the script, using the option 
# --search-terms, or writes them in a file (url encoded), given as an argument
# as well. The script makes the query on the website and returns the results on
# the standard output.
#**
TMP_DIR="${TMPDIR}"

set -ue

script() { echo "# $*"; cat; }

INFO='$Id$'
FILES=""
SEARCH_TERMS=""
BASENAME="$(basename $0)"
HITCOUNT_ONLY=false
URLENCODE=false
serverURL=http://www.ebi.ac.uk
resourcePATH=europepmc/webservices/rest/search
pageSize=1000
format=json

#** USAGE:
#**   $0 --options 'search_term_1+search_term_2' files*.inp
#**
#** OPTIONS:
#**  -n, --hit-count    Prints the number of results.
#**
#**  --ps, --page-size '10'
#**                     Modify the number of results per page (default is 1000).
#**
#**  -s, --search-terms 'crystal+structure'
#**                     Add search terms (in quotes) as arguments after this
#**                     option.
#**
#**  -U, --url-encode   Url encode all search terms.
#**
#**  --version          Prints name, version, date and author of the script.
#**
#**  --help             Prints short help message (this message) and exit.

while [ $# -gt 0 ]
do
    case $1 in
        --help|--hel|--he|--h)
            awk '/#\*/,/#\*\*/ {
                    sub("^ *#[*]?[*]?", ""); \
                    gsub("\\$0","'$(basename $0)'"); \
                    print $0
                }' $0
            exit
            ;;
        -n)
            HITCOUNT_ONLY=true
            ;;
        --options|--option)
            echo "$0: '--options' is a place-holder; " \
                 "please use '$0 --help' to get the list of available options."
            exit 2
            ;;
        --ps|--page-size)
            pageSize="$2"
            shift
            ;;
        --search-terms|--search-term|--search|--searc|--sear|--sea|--se|--s|-s)
            SEARCH_TERMS="$2"
            shift
            ;;
        --url-encode|--URL|-U)
            URLENCODE=true
            ;;
        --version|--versio|--versi|--vers|--ver|--ve|--v)
            echo $INFO
            exit
            ;;
        -*) echo "$0: unknown option '$1'" >&2
            exit 1
            ;;
        *)  FILES="${FILES} '$1'" ;;
    esac
    shift
done

echo 'files : '${FILES} 
echo 'search terms : '${SEARCH_TERMS}

eval set -- "${FILES}"

test -z "${TMP_DIR}" && TMP_DIR="/tmp"
TMP_DIR="${TMP_DIR}/tmp-${BASENAME}-$$"
mkdir "${TMP_DIR}"

## trap "rm -rf '${TMP_DIR}'" 1 2 3 15
trap "rm -rf '${TMP_DIR}'" HUP INT QUIT TERM

## set -x

if [ "${SEARCH_TERMS}" = "" ]
then 
    cat "$@"
else
    echo "${SEARCH_TERMS}"
    if [ $# -gt 0 ]
    then
        cat "$@"
    fi
fi \
| grep -vP '^\s*$|^#' \
| if [ $URLENCODE  = true ]
then
    perl -MURI::Encode -nle \
        'print URI::Encode::uri_encode($_,{encode_reserved=>1})'\
    | sed 's/%20/+/g'
else
    cat
fi \
| while read SEARCH_TERMS
do
    echo ${SEARCH_TERMS}

    request=query="${SEARCH_TERMS}"
    queryURL="$serverURL/$resourcePATH?$request"
    result="$(curl -sSL "$queryURL&format=json&pageSize=1")"

    n=$(echo "$result" | jq . | awk '/hitCount/{print $2}' | sed 's/,//')

    if [ $HITCOUNT_ONLY = true ]
    then
        echo -e $n"\t": ${SEARCH_TERMS}
    else
        if [ $n -lt $pageSize ]
        then
            j=1
        else
            j=$(expr $n / $pageSize)    
            if [ $(expr $n % $pageSize) -gt 0 ]
            then
                j=$(expr $j + 1)
            fi
        fi
        
        options="format=$format&pageSize=$pageSize"
        cursorMark='*'
        for i in $(seq 1 $j) ;
        do
            result="$(curl -sSL \
            "$queryURL&cursorMark=$cursorMark&$options")"
            echo "$result"
            cursorMark=$(echo "$result" \
               | jq . | awk '/nextCursorMark/{print $2}' | sed 's/[",]//g')
        done
    fi
done

## sleep 6

rm -rf "${TMP_DIR}"

