#! /bin/sh

# This script is intended to check if the test system works as expected.

# USAGE:
#     $0
#     $0 file
#     $0 file arguments

set -ue

echo $*

if [ $# -gt 0 ]
then
    while [ $# -gt 1 ]; do shift; done
    cat $1
fi
