#! /usr/bin/perl

# Make an option abbreviations suitable for pasting into a shell
# script.

use strict;
use warnings;

for (@ARGV) {
    my $separator = "";
    for( my $i = length($_); $i > 2; $i-- ) {
        next if substr( $_, $i-1, 1 ) eq "-";
        print $separator, substr($_,0,$i);
        $separator = "|";
    }
    print ")\n";
}
